---
project_users:
  root:
    active: true
    apikey: null
    groups:
      - admins
      - users
    # root
    password: accdeb2c4cf9536eba1bbc07d4128762d3391dc67a55b020c008fde5d0a6fb12605e090cd19da33a60d5ec850bb36c0328069834cb0013666ba9ccf2add83b4f
    permissions: []
    roles:
      - user
      - admin
    settings:
      interface:
        language: en
  foo:
    active: true
    apikey: null
    groups:
      - users
    # password
    password: 883177bbe321469c24a3ad6f5a55710da8098fafe398549b920376804121013d8fa004bcc727b8c0493858184b04272c3da9c75c7e6eebdcc6de8b5f31846d13
    permissions: []
    roles:
      - user
    settings:
      interface:
        language: en
