---
- name: trombik.localtime
  version: 1.2.1
- name: trombik.vim
  version: 1.1.4
- name: trombik.tmux
  version: 1.1.3
- name: trombik.zsh
  version: 1.1.2
- name: trombik.hostname
  version: 1.0.7
- name: trombik.git
  version: 1.1.3
- name: trombik.virtualenv
  version: 1.0.1
- name: trombik.octoprint
  version: 2.0.0
