---
- hosts:
  - virtualbox-octoprint
  - prod-octoprint
  become: yes
  become_user: root
  environment:
    http_proxy: "{{ http_proxy | default() }}"
    https_proxy: "{{ https_proxy | default() }}"
    no_proxy: "{{ no_proxy | default() }}"
  pre_tasks:
    - debug: var=hostvars[inventory_hostname]
  roles:
    - trombik.hostname
    - trombik.localtime
    - apt_get_update
    - trombik.vim
    - trombik.zsh
    - trombik.git
    - trombik.virtualenv
    - trombik.octoprint
